language: scala
scala:
  - 2.10.4
  - 2.11.1
env:
 - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
jdk:
  - openjdk6
matrix:
  include:
  - scala: 2.12.0
    jdk: oraclejdk8
